-- Populate LinkSource table.
-- Generated by atlas_linksource.py 

-- processing collection aquatic-mammals
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,0,19,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,1,15,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,2,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,3,12,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,4,18,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,5,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,6,17,"taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,7,16,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,8,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,9,11,"features");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,10,27,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,11,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,12,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,13,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,14,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(10,15,9,"");
-- processing collection atomic-elements
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(37,0,1,"definition,description,features,taxonomy");
-- processing collection dinosaurs
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,1,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,2,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,3,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,4,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(4,5,9,"");
-- processing collection edibles
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(39,0,1,"definition,description,features,taxonomy");
-- processing collection experimental
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(29,0,1,"definition,description,features,taxonomy");
-- processing collection farm-animals
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,1,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,2,11,"features");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,3,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,4,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(5,5,1,"definition,description,features,taxonomy");
-- processing collection fishes
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,1,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,2,17,"taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,3,16,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,4,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,5,11,"features");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,6,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,7,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,8,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(6,9,9,"");
-- processing collection fruits
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,1,20,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,2,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,3,17,"taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,4,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,5,21,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,6,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,7,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,8,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(26,9,1,"definition,description,features,taxonomy");
-- processing collection insects
-- processing collection megacities
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(36,0,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(36,1,1,"definition,description,features,taxonomy");
-- processing collection military-machineries
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(24,0,23,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(24,1,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(24,2,24,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(24,3,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(24,4,9,"");
-- processing collection mushrooms
-- processing collection musical-instruments
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,1,7,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,2,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,3,8,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,4,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,5,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,6,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,7,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(1,8,9,"");
-- processing collection reptiles
-- processing collection semiaquatic-rodents
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(11,0,1,"definition,description,features,taxonomy");
-- processing collection solar-system
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,1,12,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,2,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,3,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,4,26,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,5,25,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(13,6,1,"definition,description,features,taxonomy");
-- processing collection space-tech
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(28,0,1,"definition,description,features,taxonomy");
-- processing collection test
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(31,0,1,"definition,description,features,taxonomy");
-- processing collection vegetables
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,1,20,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,2,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,3,17,"taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,4,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,5,21,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,6,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,7,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,8,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,9,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(8,10,9,"");
-- processing collection wild-birds
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,0,15,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,1,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,2,12,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,3,13,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,4,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,5,17,"taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,6,16,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,7,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,8,11,"features");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,9,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,10,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,11,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,12,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(3,13,9,"");
-- processing collection wild-mammals
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,0,10,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,1,7,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,2,14,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,3,3,"description");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,4,11,"features");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,5,2,"description,facts");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,6,6,"definition");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,7,5,"");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,8,1,"definition,description,features,taxonomy");
INSERT INTO `atlas`.`linksource` (`atlascollection_id`, `linksources_order`, `externalsource_id`, `apis`) VALUES(2,9,9,"");
