-- Change discriminator column type to enumeration.

ALTER TABLE `atlas`.`translation` 
CHANGE COLUMN `discriminator` `discriminator` ENUM('OBJECT_DISPLAY', 'OBJECT_ALIASES', 'OBJECT_DEFINITION', 'OBJECT_DESCRIPTION', 'OBJECT_SAMPLE_TITLE', 'FACT_KEY', 'FACT_VALUE', 'TAXON_META_DISPLAY', 'TAXON_VALUE', 'FEATURE_META_DISPLAY', 'EXTERNAL_SOURCE_DISPLAY', 'EXTERNAL_SOURCE_DEFINITION_TEMPLATE') NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`discriminator`, `objectId`);
