-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 10:01:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kids_cademy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kids_cademy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kids_cademy` DEFAULT CHARACTER SET utf8 ;
USE `kids_cademy` ;

-- -----------------------------------------------------
-- Table `kids_cademy`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`app` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 207
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`model` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `apiLevel` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4539
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`device` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `modelId` INT(11) NOT NULL,
  `serial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `modelId`),
  INDEX `fk_device_model1_idx` (`modelId` ASC),
  CONSTRAINT `fk_device_model1`
    FOREIGN KEY (`modelId`)
    REFERENCES `kids_cademy`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17085
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`audit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `appId` INT(11) NOT NULL,
  `deviceId` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NOT NULL,
  `event` VARCHAR(45) NOT NULL,
  `parameter1` VARCHAR(80) NULL DEFAULT NULL,
  `parameter2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `appId`, `deviceId`),
  INDEX `fk_audit_device1_idx` (`deviceId` ASC),
  INDEX `fk_audit_app1_idx` (`appId` ASC),
  CONSTRAINT `fk_audit_app1`
    FOREIGN KEY (`appId`)
    REFERENCES `kids_cademy`.`app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_device1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `kids_cademy`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 391614
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`crash_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`crash_report` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `appId` INT(11) NOT NULL,
  `deviceId` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NOT NULL,
  `stackTrace` TEXT NOT NULL,
  PRIMARY KEY (`id`, `appId`, `deviceId`),
  INDEX `fk_crash_report_device1_idx` (`deviceId` ASC),
  INDEX `fk_crash_report_app1_idx` (`appId` ASC),
  CONSTRAINT `fk_crash_report_app1`
    FOREIGN KEY (`appId`)
    REFERENCES `kids_cademy`.`app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crash_report_device1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `kids_cademy`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18510
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`developer_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`developer_message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `appId` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NOT NULL,
  `text` TEXT NOT NULL,
  `developerName` VARCHAR(45) NULL DEFAULT NULL,
  `senderEmail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `appId`),
  INDEX `fk_message_app1_idx` (`appId` ASC),
  CONSTRAINT `fk_message_app1`
    FOREIGN KEY (`appId`)
    REFERENCES `kids_cademy`.`app` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`likecounter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`likecounter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NOT NULL,
  `value` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`likecounter_reasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`likecounter_reasons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `likecounter_id` INT(11) NOT NULL,
  `reasons` ENUM('NOT_INTUITIVE', 'BAD_DESIGN', 'BAD_CONTENT', 'SLOW_LOADING', 'OTHER') NOT NULL,
  PRIMARY KEY (`id`, `likecounter_id`),
  INDEX `fk_dislike_reason_like_counter_idx` (`likecounter_id` ASC),
  CONSTRAINT `fk_dislike_reason_like_counter`
    FOREIGN KEY (`likecounter_id`)
    REFERENCES `kids_cademy`.`likecounter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`no_ads_survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`no_ads_survey` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `deviceId` INT(11) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NOT NULL,
  `agree` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_no_ads_survey_device1_idx` (`deviceId` ASC),
  CONSTRAINT `fk_no_ads_survey_device1`
    FOREIGN KEY (`deviceId`)
    REFERENCES `kids_cademy`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 193
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kids_cademy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emailAddress` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emailAddress_UNIQUE` (`emailAddress` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `dtype` VARCHAR(45) NOT NULL COMMENT 'Discriminator type identify object class. Its value is derived from simple class name to lower case.',
  `state` ENUM('DEVELOPMENT', 'PUBLISHED') NOT NULL,
  `lastUpdated` TIMESTAMP NOT NULL,
  `rank` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'Object name unique per dtype. This value is used internally and is not meant to be displayed to user.',
  `display` VARCHAR(45) NOT NULL COMMENT 'Object name as displayed on user interface. It is subject to internationalization.',
  `definition` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL COMMENT 'Object description is rich text, that is, it can contains images, links and text formatting. It is stored as HTML.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_atlasobject_name` (`name` ASC, `dtype` ASC),
  INDEX `fk_atlasobject_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_atlasobject_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kids_cademy`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`instrument` (
  `id` INT NOT NULL,
  `category` SMALLINT NOT NULL,
  `sampleTitle` VARCHAR(80) NULL DEFAULT NULL,
  `sampleName` VARCHAR(45) NULL DEFAULT NULL,
  `waveformName` VARCHAR(45) NULL DEFAULT NULL,
  `date_value` BIGINT NULL DEFAULT NULL,
  `date_mask` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_instrument_atlas_object1`
    FOREIGN KEY (`id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject_aliases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject_aliases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atlasobject_id` INT NOT NULL,
  `aliases` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alias_atlas_object1_idx` (`atlasobject_id` ASC),
  CONSTRAINT `fk_alias_objec_id`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject_facts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject_facts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atlasobject_id` INT NOT NULL,
  `facts_key` VARCHAR(64) NOT NULL,
  `facts` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_atlasobject_facts_object_id` (`atlasobject_id` ASC),
  UNIQUE INDEX `uq_atlasobject_facts_key` (`atlasobject_id` ASC, `facts_key` ASC),
  CONSTRAINT `fk_fact_object1`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`bird`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`bird` (
  `id` INT NOT NULL,
  `wingspan_minimum` INT NOT NULL,
  `wingspan_maximum` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bird_object_id`
    FOREIGN KEY (`id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`animal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lifespan_minimum` INT NOT NULL,
  `lifespan_maximum` INT NOT NULL,
  `lifespan_captivity` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_animal_object_id`
    FOREIGN KEY (`id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`keyword` (
  `name` CHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`search_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`search_index` (
  `keyword_name` CHAR(20) NOT NULL,
  `atlasobject_id` INT NOT NULL,
  `relevance` INT NOT NULL,
  PRIMARY KEY (`keyword_name`, `atlasobject_id`),
  INDEX `fk_search_index_atlas_object1_idx` (`atlasobject_id` ASC),
  CONSTRAINT `fk_search_index_keyword1`
    FOREIGN KEY (`keyword_name`)
    REFERENCES `kids_cademy`.`keyword` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_search_index_atlas_object1`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`i18ntext`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`i18ntext` (
  `text_hash` INT NOT NULL,
  `language` CHAR(2) NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`text_hash`, `language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject_links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atlasobject_id` INT NOT NULL,
  `url` VARCHAR(128) NOT NULL,
  `domain` VARCHAR(45) NOT NULL,
  `display` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `iconName` VARCHAR(45) NOT NULL,
  `features` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_link_atlasobject_id` (`atlasobject_id` ASC),
  UNIQUE INDEX `uq_link_url` (`url` ASC, `atlasobject_id` ASC),
  CONSTRAINT `fk_link_atlasobject_id`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject_spreading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject_spreading` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atlasobject_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `area` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_region_atlasobject_id` (`atlasobject_id` ASC),
  UNIQUE INDEX `uq_region_area` (`atlasobject_id` ASC, `name` ASC, `area` ASC),
  CONSTRAINT `fk_region_atlasobject_id`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`atlasobject_related`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`atlasobject_related` (
  `atlasobject_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `relevance` FLOAT NOT NULL,
  PRIMARY KEY (`atlasobject_id`, `name`),
  INDEX `ix_atlasobject_related_id` (`atlasobject_id` ASC),
  INDEX `ix_atlastobject_related_name` (`name` ASC),
  CONSTRAINT `fk_atlasobject_related_id`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_atlastobject_related_name`
    FOREIGN KEY (`name`)
    REFERENCES `kids_cademy`.`atlasobject` (`name`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`collection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `display` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `iconPath` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`collection_atlasobject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`collection_atlasobject` (
  `collection_id` INT NOT NULL,
  `atlasobject_id` INT NOT NULL,
  PRIMARY KEY (`collection_id`, `atlasobject_id`),
  INDEX `fk_collection_has_atlasobject_atlasobject1_idx` (`atlasobject_id` ASC),
  INDEX `fk_collection_has_atlasobject_collection1_idx` (`collection_id` ASC),
  CONSTRAINT `fk_collection_has_atlasobject_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `kids_cademy`.`collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collection_has_atlasobject_atlasobject1`
    FOREIGN KEY (`atlasobject_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`mediafile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`mediafile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mediaType` VARCHAR(45) NOT NULL COMMENT 'Media type, also known as MIME type, as classified by IANA.',
  `kind` VARCHAR(45) NULL COMMENT 'Optional media kind. It can be used to classify media files - perhaps functionally but not limited to, for example \'icon\'.',
  `fileName` VARCHAR(45) NOT NULL,
  `fileSize` INT NULL,
  `uploadDate` DATETIME NOT NULL,
  `license` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `source` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kids_cademy`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pictures_id` INT NULL COMMENT 'Atlas object foreign key for pictures list. It cannot be not null because of the way update queries are generated by JPA.',
  `pictures_order` SMALLINT NULL,
  `name` VARCHAR(45) NOT NULL,
  `uploadDate` DATETIME NOT NULL,
  `source` TEXT NULL,
  `caption` TEXT NULL,
  `fileName` VARCHAR(45) NOT NULL,
  `fileSize` INT NOT NULL,
  `width` SMALLINT NOT NULL,
  `height` SMALLINT NOT NULL,
  INDEX `IX_PICTURE_ATLASOBJECT_ID` (`pictures_id` ASC),
  UNIQUE INDEX `UQ_PICTURE_FILE_NAME` (`pictures_id` ASC, `fileName` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ATLASOBJECT_PICTUES_ATLASOBJECT_ID`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `kids_cademy`.`atlasobject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `kids_cademy` ;

-- -----------------------------------------------------
-- Placeholder table for view `kids_cademy`.`app_load`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`app_load` (`id` INT, `appId` INT, `timestamp` INT, `value` INT);

-- -----------------------------------------------------
-- Placeholder table for view `kids_cademy`.`instrument_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`instrument_object` (`id` INT, `state` INT, `lastUpdated` INT, `rank` INT, `category` INT, `name` INT, `display` INT, `description` INT, `sampleTitle` INT, `sampleName` INT, `waveformName` INT, `date_value` INT, `date_mask` INT);

-- -----------------------------------------------------
-- Placeholder table for view `kids_cademy`.`uiobject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kids_cademy`.`uiobject` (`id` INT, `dtype` INT, `name` INT, `display` INT, `iconName` INT);

-- -----------------------------------------------------
-- View `kids_cademy`.`app_load`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kids_cademy`.`app_load`;
USE `kids_cademy`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `kids_cademy`.`app_load` AS select `kids_cademy`.`audit`.`id` AS `id`,`kids_cademy`.`audit`.`appId` AS `appId`,`kids_cademy`.`audit`.`timestamp` AS `timestamp`,count(0) AS `value` from `kids_cademy`.`audit` where (`kids_cademy`.`audit`.`event` = 'APP_LOAD') group by year(`kids_cademy`.`audit`.`timestamp`),month(`kids_cademy`.`audit`.`timestamp`),dayofmonth(`kids_cademy`.`audit`.`timestamp`);

-- -----------------------------------------------------
-- View `kids_cademy`.`instrument_object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kids_cademy`.`instrument_object`;
USE `kids_cademy`;
CREATE  OR REPLACE VIEW `instrument_object` AS

SELECT
	i.id,
    o.state,
    o.lastUpdated,
    o.rank,
    i.category,
    o.name,
    o.display,
    o.description,
    i.sampleTitle,
    i.sampleName,
    i.waveformName,
    i.date_value,
    i.date_mask
    
FROM instrument i
JOIN atlasobject o ON i.id=o.id;

-- -----------------------------------------------------
-- View `kids_cademy`.`uiobject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kids_cademy`.`uiobject`;
USE `kids_cademy`;
CREATE  OR REPLACE VIEW `uiobject` AS

SELECT DISTINCT
	o.id,
    o.dtype,
    o.name,
    o.display,
    CASE WHEN p.name='icon' THEN p.fileName ELSE null END AS iconName

FROM atlasobject o 
JOIN picture p ON o.id=p.pictures_id AND p.pictures_order=0

UNION

SELECT 
	o.id,
    o.dtype,
    o.name,
    o.display,
    NULL AS iconName

FROM atlasobject o 
LEFT JOIN picture p ON o.id=p.pictures_id 
WHERE p.pictures_id IS NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
