UPDATE atlas.featuremeta SET display='Lifespan' WHERE name='lifespan';
UPDATE atlas.featuremeta SET display='Lifespan Record' WHERE name='lifespan.record';
UPDATE atlas.featuremeta SET display='Lifespan in Captivity' WHERE name='lifespan.captivity';
UPDATE atlas.featuremeta SET display='Body Length' WHERE name='length';
UPDATE atlas.featuremeta SET display='Bill Length' WHERE name='length.bill';
UPDATE atlas.featuremeta SET display='Tail Length' WHERE name='length.tail';
UPDATE atlas.featuremeta SET display='Claws Size' WHERE name='length.claw';
UPDATE atlas.featuremeta SET display='Height' WHERE name='height';
UPDATE atlas.featuremeta SET display='Height at Shoulder' WHERE name='height.shoulder';
UPDATE atlas.featuremeta SET display='Height at Hip' WHERE name='height.hip';
UPDATE atlas.featuremeta SET display='Wingspan' WHERE name='wingspan';
UPDATE atlas.featuremeta SET display='Weight' WHERE name='weight';
UPDATE atlas.featuremeta SET display='Speed' WHERE name='speed';
UPDATE atlas.featuremeta SET display='Full Speed' WHERE name='speed.full';
UPDATE atlas.featuremeta SET display='Gliding Speed' WHERE name='speed.gliding';
UPDATE atlas.featuremeta SET display='Diving Speed' WHERE name='speed.diving';
UPDATE atlas.featuremeta SET display='Flying Height' WHERE name='flying.height';
UPDATE atlas.featuremeta SET display='Elevation' WHERE name='elevation';
UPDATE atlas.featuremeta SET display='Diving Depth' WHERE name='depth';
UPDATE atlas.featuremeta SET display='Food Energy' WHERE name='nutrient.calories';
UPDATE atlas.featuremeta SET display='Protein' WHERE name='nutrient.protein';
UPDATE atlas.featuremeta SET display='Total Fat' WHERE name='nutrient.fat';
UPDATE atlas.featuremeta SET display='Sugars' WHERE name='nutrient.sugars';
UPDATE atlas.featuremeta SET display='Dietary Fiber' WHERE name='nutrient.dietary.fiber';
UPDATE atlas.featuremeta SET display='Drinking Alcohol' WHERE name='nutrient.ethanol';
UPDATE atlas.featuremeta SET display='Carbohydrates' WHERE name='nutrient.carbohydrates';
UPDATE atlas.featuremeta SET display='Vitamin A' WHERE name='nutrient.vitamin.a';
UPDATE atlas.featuremeta SET display='Thiamine' WHERE name='nutrient.vitamin.thiamine';
UPDATE atlas.featuremeta SET display='Niacin' WHERE name='nutrient.vitamin.niacin';
UPDATE atlas.featuremeta SET display='Vitamin B6' WHERE name='nutrient.vitamin.b6';
UPDATE atlas.featuremeta SET display='Vitamin C' WHERE name='nutrient.vitamin.c';
UPDATE atlas.featuremeta SET display='Vitamin E' WHERE name='nutrient.vitamin.e';
UPDATE atlas.featuremeta SET display='Vitamin K' WHERE name='nutrient.vitamin.k';
UPDATE atlas.featuremeta SET display='Vitamin D' WHERE name='nutrient.vitamin.d';
UPDATE atlas.featuremeta SET display='Magnesium' WHERE name='nutrient.mineral.magnesium';
UPDATE atlas.featuremeta SET display='Manganese' WHERE name='nutrient.mineral.manganese';
UPDATE atlas.featuremeta SET display='Phosphorus' WHERE name='nutrient.mineral.phosphorus';
UPDATE atlas.featuremeta SET display='Potassium' WHERE name='nutrient.mineral.potassium';
UPDATE atlas.featuremeta SET display='Calcium' WHERE name='nutrient.mineral.calcium';
UPDATE atlas.featuremeta SET display='Iron' WHERE name='nutrient.mineral.iron';
UPDATE atlas.featuremeta SET display='Vitamin B12' WHERE name='nutrient.vitamin.b12';
UPDATE atlas.featuremeta SET display='Sodium' WHERE name='nutrient.mineral.sodium';
UPDATE atlas.featuremeta SET display='Zinc' WHERE name='nutrient.mineral.zinc';
UPDATE atlas.featuremeta SET display='Water' WHERE name='nutrient.water';
UPDATE atlas.featuremeta SET display='Starch' WHERE name='nutrient.starch';
UPDATE atlas.featuremeta SET display='Width' WHERE name='width';
UPDATE atlas.featuremeta SET display='Orbit Aphelion' WHERE name='orbit.aphelion';
UPDATE atlas.featuremeta SET display='Orbit Perihelion' WHERE name='orbit.perihelion';
UPDATE atlas.featuremeta SET display='Crew' WHERE name='crew';
UPDATE atlas.featuremeta SET display='Range' WHERE name='range';
UPDATE atlas.featuremeta SET display='Maximum Range' WHERE name='range.maximum';
UPDATE atlas.featuremeta SET display='Engine Power' WHERE name='engine.power';
UPDATE atlas.featuremeta SET display='Ship Displacement' WHERE name='ship.displacement';
UPDATE atlas.featuremeta SET display='Ship Beam' WHERE name='ship.beam';
UPDATE atlas.featuremeta SET display='Maximum Ship Beam' WHERE name='ship.beam.maximum';
UPDATE atlas.featuremeta SET display='Ship Draft' WHERE name='ship.draft';
UPDATE atlas.featuremeta SET display='Mean Radius' WHERE name='radius';
UPDATE atlas.featuremeta SET display='Mass' WHERE name='mass';
UPDATE atlas.featuremeta SET display='Mean Density' WHERE name='density';
UPDATE atlas.featuremeta SET display='Mean Orbit Radius' WHERE name='orbit.radius';
UPDATE atlas.featuremeta SET display='Orbital Period' WHERE name='orbit.period';
UPDATE atlas.featuremeta SET display='Orbital Speed' WHERE name='orbit.speed';
UPDATE atlas.featuremeta SET display='Albedo' WHERE name='albedo';
UPDATE atlas.featuremeta SET display='Escape velocity' WHERE name='speed.escape';
UPDATE atlas.featuremeta SET display='Surface Gravity' WHERE name='gravity';
UPDATE atlas.featuremeta SET display='Orbital Eccentricity' WHERE name='orbit.eccentricity';
UPDATE atlas.featuremeta SET display='Rotation Period' WHERE name='rotation.period';
UPDATE atlas.featuremeta SET display='Axial Tilt' WHERE name='axial.tilt';
UPDATE atlas.featuremeta SET display='Urban Population' WHERE name='population.urban';
UPDATE atlas.featuremeta SET display='Metro Population' WHERE name='population.metro';
UPDATE atlas.featuremeta SET display='Population Density' WHERE name='population.density';
UPDATE atlas.featuremeta SET display='Urban Area' WHERE name='area.urban';
UPDATE atlas.featuremeta SET display='Metro Area' WHERE name='area.metro';
UPDATE atlas.featuremeta SET display='Total GVA' WHERE name='gva.total';
UPDATE atlas.featuremeta SET display='GVA per capita' WHERE name='gva.percapita';
UPDATE atlas.featuremeta SET display='Speed Record' WHERE name='speed.record';
UPDATE atlas.featuremeta SET display='Riboflavin' WHERE name='nutrient.vitamin.riboflavin';
UPDATE atlas.featuremeta SET display='Pantothenic' WHERE name='nutrient.vitamin.pantothenic.acid';
UPDATE atlas.featuremeta SET display='Folate' WHERE name='nutrient.vitamin.folate';
UPDATE atlas.featuremeta SET display='Choline' WHERE name='nutrient.vitamin.choline';
UPDATE atlas.featuremeta SET display='Copper' WHERE name='nutrient.mineral.copper';
UPDATE atlas.featuremeta SET display='Selenium' WHERE name='nutrient.mineral.selenium';
